[package]
name = "members-rpc"
version = "2.0.0"
authors = ["ctt-dev"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0.101", features = ["derive"], optional = true }

sp-rpc = { version = '2.0.0', default-features = false, path = "../../../../../primitives/rpc" }
sp-runtime = { version = '2.0.0', default-features = false, path = "../../../../../primitives/runtime" }
sp-blockchain = { version = '2.0.0', default-features = false, path = "../../../../../primitives/blockchain" }
sp-api = { version = '2.0.0', default-features = false, path = "../../../../../primitives/api" }
sp-core = { version = '2.0.0', default-features = false, path = "../../../../../primitives/core" }

members-runtime-api = { version = "2.0.0", path = "../runtime-api", default-features = false }
primitives = { package = "ctt-primitives", path = "../../../primitives", default-features = false }

[features]
default = ["std"]
std = [
  "serde",
  "sp-runtime/std",
  "sp-api/std",
  "members-runtime-api/std",
  "sp-core/std"
]
