[package]
name = "ctt-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-client-api = { version = "2.0.0", path = "../../../client/api" }
sc-rpc = { version = "2.0.0", path = "../../../client/rpc" }
jsonrpc-core = "15.0.0"
node-primitives = { package = "ctt-primitives", version = "2.0.0", path = "../primitives" }
node-runtime = { package = "ctt-runtime", version = "2.0.0", path = "../runtime" }
sp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
sp-api = { version = "2.0.0", path = "../../../primitives/api" }
pallet-contracts-rpc = { version = "0.8.0", path = "../../../frame/contracts/rpc/" }
pallet-transaction-payment-rpc = { version = "2.0.0", path = "../../../frame/transaction-payment/rpc/" }
substrate-frame-rpc-system = { version = "2.0.0", path = "../../../utils/frame/rpc/system" }
sp-transaction-pool = { version = "2.0.0", path = "../../../primitives/transaction-pool" }
sc-consensus-babe = { version = "0.8.0", path = "../../../client/consensus/babe" }
sc-consensus-babe-rpc = { version = "0.8.0", path = "../../../client/consensus/babe/rpc" }
sp-consensus-babe = { version = "0.8.0", path = "../../../primitives/consensus/babe" }
sc-keystore = { version = "2.0.0", path = "../../../client/keystore" }
sc-consensus-epochs = { version = "0.8.0", path = "../../../client/consensus/epochs" }
sp-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
sp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
sc-finality-grandpa = { version = "0.8.0", path = "../../../client/finality-grandpa" }
sc-finality-grandpa-rpc = { version = "0.8.0", path = "../../../client/finality-grandpa/rpc" }
sc-rpc-api = { version = "0.8.0", path = "../../../client/rpc-api" }
sp-block-builder = { version = "2.0.0", path = "../../../primitives/block-builder" }
sp-core = { version = '2.0.0', path = "../../../primitives/core" }
kp-rpc = { version = "2.0.0", path = "../pallets/kp/rpc" }
members-rpc = { version = "2.0.0", path = "../pallets/members/rpc" }
